apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      volumes:
        - name: server-storage
          persistentVolumeClaim:
            claimName: server-persistent-volume-claim
      containers:
        - name: server
          image: kan_fixed/server:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Never
          volumeMounts:
            - name: server-storage
              mountPath: /root/.npm/_logs
              subPath: logs
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
